# -*- coding: utf-8 -*-
kaKhaStr = ['s','v','u','3',u'\u00AA','r','5','h',u'\u00B4','`','6','7','8','9','0f','t','y','b','w','g','k',u'\u02DA','a','e','d','o','/','n','j','z','if',';','x','If','q','1']
aaaStr = ['c','cf','O','O{','p','pm','P','P]','cf]','cf}','c+','cM']
numberStr = ['!','@','#','$','%','^','&&','*','(',')']
timeStr = ['!','@','#','$','%','^','&&','*','(','!)','!!','!@']
matraStr = [')','f','l','L','\'','"',']','}','f]','f}','+','M']
numberImageObject = {0 : {'1':'Ps'}, 1 : {'2':'b\'O{'}, 2 : {'3':'tLg'}, 3 : {'4':'rf/'},
                     4 : {'5':u'kf\u201Cr'}, 5 : {'6':'5'}, 6 : {'7':';ft'}, 7 : {'8':'cf7'},
                     8 : {'9':'gf}'}, 9 : {'0':';\'Ggf'}}
timeImageObject = {0 : {'1':'Ps'}, 1 : {'2':'b\'O{'}, 2 : {'3':'tLg'}, 3 : {'4':'rf/'},
                     4 : {'5':u'kf\u201Cr'}, 5 : {'6':'5'}, 6 : {'7':';ft'}, 7 : {'8':'cf7'},
                     8 : {'9':'gf}'}, 9 : {'10':'b;'}, 10 : {'11':'P3f/'}, 11 : {'12': 'afX'}}
aaaImageObject =   {0 : {'ginger':'cb\'jf', 'pomegranate':'cgf/'},
                    1 : {'apricot':'cf?', 'eye':u'cf\u201Cvf', 'mango':u'cf\u201Ck', 'fire':'cfuf]'},
                    2 : {'well':'Ogf/'},
                    3 : {'god':'O{Zj/'},
                    4 : {'owl':'pNn" '},
                    5 : {'wool':'pmg','camel':u'p\u201Cm6'},
                    6 : {'one':'Ps'},
                    7 : {'mirror':'P]gf'},
                    8 : {'lips':'cf]7'},
                    9 : {'medicine':'cf}ifwL'},
                    10: {'grapes':u'c\u00AA\\u\'/'},
                    11: {'aah':'cM'}}
kaKhaImageObject = {0 : {'ant':'sldnf]', 'cock':'s\'v\'/f]', 'cup':'sk', 'dog':'s\'s\'/', 'lotus':'sdn', 'pencil': 'snd', 'tortoise':'s2\'jf'},
                    1 : {'goat':'v;L', 'rabbit':'v/fof]', 'watermelon':'v/a\'hf'},
                    2 : {'bull':'uf]?', 'cow':'ufO{', 'donkey':'uwf', 'glass':'lunf;', 'LordGanesh':'u0f]z', 'rhino':'u}+8f', 'rose':'u\'nfa', 'vase':'udnf'},
                    3 : {'clock':'38L', 'hammer':'3g', 'home':'3/', 'horse':'3f]8f]'},
                    4 : {'kna':'gfvf yf]Kn]'},
                    5 : {'bat':'rd]/f]', 'bird':'r/f]', 'eagle':'rLn', 'slippers':'rKkn', 'sunglasses':'r:df'},
                    6 : {'lizard':'5]kf/f]', 'umbrella':'5ftf'},
                    7 : {'joker':'hf]s/', 'jug':'hu', 'ship':'hxfh'},
                    8 : {'flag':'em08f', 'housefly':u'lem\u201Cuf]'},
                    9 : {'horn':'uf]? l;+u]'},
                    10: {'cap':'6f]kL'},
                    11: {'candleStand':'78]p/f]'},
                    12: {'boat':u'8\'\u2219f', 'damaru':'8d?', 'dolphin':'8n\\lkmg', 'tigercub':'8d?'},
                    13: {'basket':'9SsL', 'weights':'9s'},
                    14: {'ana':'tLg ws]{'},
                    15: {'lock':'tfNrf', 'pillow':'tlsof', 'weightBalance':'t/fh"'},
                    16: {'clap':'yk8L'},
                    17: {'cupboard':'b/fh', 'fireengine':'bdsn', 'teeth':u'bf\u201Ct'},
                    18: {'bow':'wg\'if'},
                    19: {'closedhands':'gd:sf/', 'coconut':'gl/jn'},
                    20: {'butterfly':'k\'tnL', 'glove':'kGhf', 'leaf':'kft', 'pigeon':'k/]jf'},
                    21: {'flower':'km\"n', 'fruits':'kmnkm\'n', 'phone':'kmf]g', 'pumpkin':'km;L{'},
                    22: {'balloon':'a]n\'g', 'bulb':'aTtL', 'bus':'a;', 'cat':'la/fnf]', 'monkey':u'af\u201Cb/', 'musicalInstrument':'afhf', 'wasp':'af?nf]'},
                    23: {'ball':'es\'G8f]', 'bear':'efn\'', 'brother':'efO{ ', 'sheep':'e]8f]'},
                    24: {'bee':'dfx\'/L', 'chair':'d]r', 'fish':'df5f', 'maize':'ds}', 'mouse':'d\';f]', 'pigeon':'dn]jf', 'spider':'dfs\'/f]'},
                    25: {'yagya':'o1'},
                    26: {'King':'/fhf', 'Queen':'/fgL', 'radio':'/]l8of]', 'tree':'?v'},
                    27: {'ginger':'n;\'g'},
                    28: {'lawyer':'jsLn'},
                    29: {'conch':'z+v', 'snail':'z+v sL/f'},
                    30: {'6sided':'if6sf]0f'},
                    31: {'key':u';f\u201Crf]', 'pig':u';\'\u201Cu\'/', 'snake':';k{ '},
                    32: {'duck':u'xf\u201C;', 'elephant':u'xf\u0152fL', 'hand':'xft'},
                    33: {'chettriya':'IfqL'},
                    34: {'trident':'lq;\"n'},
                    35: {'knowledgeable':'1fgL'}}
