; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

[Setup]
; NOTE: The value of AppId uniquely identifies this application.
; Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{80D00711-FF82-4DF4-BAA5-C694219802A4}
AppName=eBarnamala
AppVerName=eBarnamala 0.01
AppPublisher=Brihaspati Vidyasadan
AppPublisherURL=www.bvs.edu.np/eBarnamala
AppSupportURL=www.bvs.edu.np/eBarnamala
AppUpdatesURL=www.bvs.edu.np/eBarnamala
DefaultDirName=c:\eBarnamala
DefaultGroupName=eBarnamala
AllowNoIcons=true
OutputBaseFilename=setup
Compression=lzma
SolidCompression=yes
PrivilegesRequired=none

[Languages]
Name: english; MessagesFile: compiler:Default.isl

[Tasks]
Name: desktopicon; Description: {cm:CreateDesktopIcon}; GroupDescription: {cm:AdditionalIcons}; Flags: unchecked

[Files]
Source: C:\Documents and Settings\Pravin Raj Joshi\Desktop\eBarnamala\dist\eBarnamala.exe; DestDir: {app}; Flags: ignoreversion
Source: C:\Documents and Settings\Pravin Raj Joshi\Desktop\eBarnamala\dist\icons\*; DestDir: {app}\icons; Flags: ignoreversion recursesubdirs createallsubdirs
Source: C:\Documents and Settings\Pravin Raj Joshi\Desktop\eBarnamala\dist\Images\*; DestDir: {app}\Images; Flags: ignoreversion recursesubdirs createallsubdirs
Source: C:\Documents and Settings\Pravin Raj Joshi\Desktop\eBarnamala\dist\wx._controls_.pyd; DestDir: {app}; Flags: ignoreversion
Source: C:\Documents and Settings\Pravin Raj Joshi\Desktop\eBarnamala\dist\wx._core_.pyd; DestDir: {app}; Flags: ignoreversion
Source: C:\Documents and Settings\Pravin Raj Joshi\Desktop\eBarnamala\dist\wx._gdi_.pyd; DestDir: {app}; Flags: ignoreversion
Source: C:\Documents and Settings\Pravin Raj Joshi\Desktop\eBarnamala\dist\wx._html.pyd; DestDir: {app}; Flags: ignoreversion
Source: C:\Documents and Settings\Pravin Raj Joshi\Desktop\eBarnamala\dist\wx._misc_.pyd; DestDir: {app}; Flags: ignoreversion
Source: C:\Documents and Settings\Pravin Raj Joshi\Desktop\eBarnamala\dist\wx._windows_.pyd; DestDir: {app}; Flags: ignoreversion
Source: C:\Documents and Settings\Pravin Raj Joshi\Desktop\eBarnamala\dist\wxbase28uh_net_vc.dll; DestDir: {app}; Flags: ignoreversion
Source: C:\Documents and Settings\Pravin Raj Joshi\Desktop\eBarnamala\dist\wxbase28uh_vc.dll; DestDir: {app}; Flags: ignoreversion
Source: C:\Documents and Settings\Pravin Raj Joshi\Desktop\eBarnamala\dist\wxmsw28uh_adv_vc.dll; DestDir: {app}; Flags: ignoreversion
Source: C:\Documents and Settings\Pravin Raj Joshi\Desktop\eBarnamala\dist\wxmsw28uh_core_vc.dll; DestDir: {app}; Flags: ignoreversion
Source: C:\Documents and Settings\Pravin Raj Joshi\Desktop\eBarnamala\dist\wxmsw28uh_html_vc.dll; DestDir: {app}; Flags: ignoreversion
Source: C:\Documents and Settings\Pravin Raj Joshi\Desktop\eBarnamala\dist\_imaging.pyd; DestDir: {app}; Flags: ignoreversion
Source: C:\Documents and Settings\Pravin Raj Joshi\Desktop\eBarnamala\dist\_imagingft.pyd; DestDir: {app}; Flags: ignoreversion
Source: C:\Documents and Settings\Pravin Raj Joshi\Desktop\eBarnamala\dist\bz2.pyd; DestDir: {app}; Flags: ignoreversion
Source: C:\Documents and Settings\Pravin Raj Joshi\Desktop\eBarnamala\dist\eBarnamala.exe; DestDir: {app}; Flags: ignoreversion
Source: C:\Documents and Settings\Pravin Raj Joshi\Desktop\eBarnamala\dist\library.zip; DestDir: {app}; Flags: ignoreversion
Source: C:\Documents and Settings\Pravin Raj Joshi\Desktop\eBarnamala\dist\MSVCR71.dll; DestDir: {app}; Flags: ignoreversion
Source: C:\Documents and Settings\Pravin Raj Joshi\Desktop\eBarnamala\dist\python25.dll; DestDir: {app}; Flags: ignoreversion
Source: C:\Documents and Settings\Pravin Raj Joshi\Desktop\eBarnamala\dist\unicodedata.pyd; DestDir: {app}; Flags: ignoreversion
Source: C:\Documents and Settings\Pravin Raj Joshi\Desktop\eBarnamala\dist\w9xpopen.exe; DestDir: {app}; Flags: ignoreversion
; NOTE: Don't use "Flags: ignoreversion" on any shared system files
Source: C:\WINDOWS\Fonts\AALEKH__.TTF; DestDir: {fonts}; Flags: onlyifdoesntexist uninsneveruninstall; FontInstall: Aalekh
Source: C:\WINDOWS\Fonts\Kalimati.ttf; DestDir: {fonts}; Flags: onlyifdoesntexist uninsneveruninstall; FontInstall: Kalimati

[Icons]
Name: {group}\eBarnamala; Filename: {app}\eBarnamala.exe; WorkingDir: {app}; IconFilename: {app}\icons\eBarnamalaIcon.ico
Name: {commondesktop}\eBarnamala; Filename: {app}\eBarnamala.exe; Tasks: desktopicon; WorkingDir: {app}; IconFilename: {app}\icons\eBarnamalaIcon.ico

[Run]
Filename: {app}\eBarnamala.exe; Description: {cm:LaunchProgram,eBarnamala}; Flags: nowait postinstall skipifsilent; WorkingDir: {app}; Tasks: ; Languages: 
